version: '3.1'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    env_file: .env
  database:
    image: postgres:12-alpine
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
